services:

  books-app:
    build: .
    container_name: books-app
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - COUNTER_SERVICE_URL=http://counter-book:3001
    volumes:
      - ./:/app
      - ./server.log:/app/server.log
    depends_on:
      - counter-book
  counter-book:
    image: kecilusty/counter-book
    container_name: counter-book
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_HOST=redis://storage
    depends_on:
      - storage   
  storage:
    image: redis:latest
    container_name: storage
    volumes:
      - ./data:/data
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass